version: '2017.{build}'
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
nuget:
  disable_publish_on_pr: true
build_script:
- ps: ./netcore.ps1 -build
test_script:
- ps: >-

    ./netcore.ps1 -test
    
    If (($env:APPVEYOR_REPO_BRANCH -eq "master") -and (!$env:APPVEYOR_PULL_REQUEST_NUMBER)) {

    .\netcore.ps1 -updatexml -pack 


    }
deploy:
- provider: NuGet
  api_key:
    secure: Sd5YqTAynv1NxMSJqSw16bmA7dUO0nroLzp4zr050H0sad+8eifLB/Z8fy9sIhDU
  on:
    branch: master
    appveyor_repo_tag: true
on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))